package com.TravelMedicineAdvisory.Server.core.queue;

public enum JobType {
    EMAIL_VERIFICATION,
    EMAIL_PASSWORD_RESET,
    EMAIL_PASSWORD_CHANGED,
    EMAIL_EMPLOYEE_INVITATION,
    EMAIL_GENERIC,
    EMAIL_CREDIT_PURCHASE,
    EMAIL_CREDIT_ALLOCATION,
    EMAIL_CREDIT_REQUEST_APPROVED,
    EMAIL_CREDIT_REQUEST_REJECTED,
    EMAIL_EMPLOYEE_STATUS_CHANGED,
    EMAIL_EMPLOYEE_REMOVED,
    EMAIL_API_KEY_CREATED,
    EMAIL_API_KEY_REVOKED,
    EMAIL_TRAVEL_PLAN_CREATED,
    EMAIL_LOGIN_ALERT,
    EMAIL_INVOICE_AVAILABLE,
    EMAIL_ONBOARDING_REMINDER,
    EMAIL_TWO_FACTOR_ENABLED,
    EMAIL_TWO_FACTOR_DISABLED,
    EMAIL_BILLING_CURRENCY_CHANGED,
    EMAIL_DATA_EXPORT,
    EMAIL_INVITATION_ACCEPTED,
    EMAIL_CREDIT_REQUEST_SUBMITTED,
    EMAIL_COMPANY_ADMIN_ONBOARDING
}
