# ---- Build stage ----
FROM eclipse-temurin:25-jdk AS build

WORKDIR /app

# Copy Maven wrapper and POM first for dependency caching
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN chmod +x mvnw && ./mvnw dependency:go-offline -B

# Copy source and build
COPY src/ src/
RUN ./mvnw clean package -DskipTests -B

# ---- Runtime stage ----
FROM eclipse-temurin:25-jre

WORKDIR /app

# Application Settings
ARG APP_ENV=debug
ARG SERVER_PORT=8080
ARG APP_FRONTEND_URL=http://localhost:3000
ARG APP_HOST=http://localhost:8080

# Database Configuration
ARG SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/travel-medicine-advisory
ARG SPRING_DATASOURCE_USERNAME=postgres
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_JPA_HIBERNATE_DDL_AUTO=update

# Security
ARG JWT_SECRET
ARG APP_API_KEY

# Mail
ARG SPRING_MAIL_HOST=smtp.resend.com
ARG SPRING_MAIL_PORT=587
ARG SPRING_MAIL_USERNAME=resend
ARG SPRING_MAIL_PASSWORD

# Redis
ARG REDIS_HOST=localhost
ARG REDIS_PORT=6379

# Storage
ARG APP_STORAGE_PATH=storage/upload
ARG APP_STORAGE_BASE_URL=http://localhost:8080/storage/upload

# Flutterwave Payment
ARG FLUTTERWAVE_PUBLIC_KEY
ARG FLUTTERWAVE_SECRET_KEY
ARG FLUTTERWAVE_ENCRYPTION_KEY
ARG FLUTTERWAVE_CALLBACK_URL=http://localhost:3000/payment/callback
ARG FLUTTERWAVE_WEBHOOK_URL=http://localhost:8080/api/v1/payments/webhook/flutterwave

ENV APP_ENV=${APP_ENV} \
    SERVER_PORT=${SERVER_PORT} \
    APP_FRONTEND_URL=${APP_FRONTEND_URL} \
    APP_HOST=${APP_HOST} \
    SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL} \
    SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} \
    SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
    SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO} \
    JWT_SECRET=${JWT_SECRET} \
    APP_API_KEY=${APP_API_KEY} \
    SPRING_MAIL_HOST=${SPRING_MAIL_HOST} \
    SPRING_MAIL_PORT=${SPRING_MAIL_PORT} \
    SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME} \
    SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD} \
    REDIS_HOST=${REDIS_HOST} \
    REDIS_PORT=${REDIS_PORT} \
    APP_STORAGE_PATH=${APP_STORAGE_PATH} \
    APP_STORAGE_BASE_URL=${APP_STORAGE_BASE_URL} \
    FLUTTERWAVE_PUBLIC_KEY=${FLUTTERWAVE_PUBLIC_KEY} \
    FLUTTERWAVE_SECRET_KEY=${FLUTTERWAVE_SECRET_KEY} \
    FLUTTERWAVE_ENCRYPTION_KEY=${FLUTTERWAVE_ENCRYPTION_KEY} \
    FLUTTERWAVE_CALLBACK_URL=${FLUTTERWAVE_CALLBACK_URL} \
    FLUTTERWAVE_WEBHOOK_URL=${FLUTTERWAVE_WEBHOOK_URL}

# Create storage directory
RUN mkdir -p /app/storage/upload

COPY --from=build /app/target/Server-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
