# ---- Build stage ----
FROM eclipse-temurin:25-jdk AS build

WORKDIR /app

# Copy Maven wrapper and POM first for dependency caching
COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN chmod +x mvnw && ./mvnw dependency:go-offline -B

# Copy source and build
COPY src/ src/
RUN ./mvnw clean package -DskipTests -B

# ---- Runtime stage ----
FROM eclipse-temurin:25-jre

WORKDIR /app

# Application Settings
ARG APP_ENV
ARG SERVER_PORT
ARG APP_FRONTEND_URL
ARG APP_HOST

# Database Configuration
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_JPA_HIBERNATE_DDL_AUTO

# Security
ARG JWT_SECRET
ARG APP_API_KEY

# Mail
ARG SPRING_MAIL_HOST
ARG SPRING_MAIL_PORT
ARG SPRING_MAIL_USERNAME
ARG SPRING_MAIL_PASSWORD

# Redis
ARG REDIS_HOST
ARG REDIS_PORT

# Storage
ARG APP_STORAGE_PATH
ARG APP_STORAGE_BASE_URL

# Flutterwave Payment
ARG FLUTTERWAVE_PUBLIC_KEY
ARG FLUTTERWAVE_SECRET_KEY
ARG FLUTTERWAVE_ENCRYPTION_KEY
ARG FLUTTERWAVE_CALLBACK_URL
ARG FLUTTERWAVE_WEBHOOK_URL

ENV APP_ENV=${APP_ENV} \
    SERVER_PORT=${SERVER_PORT} \
    APP_FRONTEND_URL=${APP_FRONTEND_URL} \
    APP_HOST=${APP_HOST} \
    SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL} \
    SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} \
    SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
    SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO} \
    JWT_SECRET=${JWT_SECRET} \
    APP_API_KEY=${APP_API_KEY} \
    SPRING_MAIL_HOST=${SPRING_MAIL_HOST} \
    SPRING_MAIL_PORT=${SPRING_MAIL_PORT} \
    SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME} \
    SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD} \
    REDIS_HOST=${REDIS_HOST} \
    REDIS_PORT=${REDIS_PORT} \
    APP_STORAGE_PATH=${APP_STORAGE_PATH} \
    APP_STORAGE_BASE_URL=${APP_STORAGE_BASE_URL} \
    FLUTTERWAVE_PUBLIC_KEY=${FLUTTERWAVE_PUBLIC_KEY} \
    FLUTTERWAVE_SECRET_KEY=${FLUTTERWAVE_SECRET_KEY} \
    FLUTTERWAVE_ENCRYPTION_KEY=${FLUTTERWAVE_ENCRYPTION_KEY} \
    FLUTTERWAVE_CALLBACK_URL=${FLUTTERWAVE_CALLBACK_URL} \
    FLUTTERWAVE_WEBHOOK_URL=${FLUTTERWAVE_WEBHOOK_URL}

# Create storage directory
RUN mkdir -p /app/storage/upload

COPY --from=build /app/target/Server-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
