# ---- Build stage ----
FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /app

COPY mvnw pom.xml ./
RUN ./mvnw dependency:resolve -B

COPY src ./src
RUN ./mvnw clean package -DskipTests -B

# ---- Runtime stage ----
FROM eclipse-temurin:25-jre

WORKDIR /app

ARG APP_ENV=prod
ARG SERVER_PORT=8080
ARG APP_FRONTEND_URL
ARG APP_HOST
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_JPA_HIBERNATE_DDL_AUTO
ARG JWT_SECRET=changeme
ARG APP_API_KEY=changeme
ARG SPRING_MAIL_HOST
ARG SPRING_MAIL_PORT
ARG SPRING_MAIL_USERNAME
ARG SPRING_MAIL_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT
ARG APP_STORAGE_PATH
ARG APP_STORAGE_BASE_URL
ARG FLUTTERWAVE_PUBLIC_KEY
ARG FLUTTERWAVE_SECRET_KEY
ARG FLUTTERWAVE_ENCRYPTION_KEY
ARG FLUTTERWAVE_CALLBACK_URL
ARG FLUTTERWAVE_WEBHOOK_URL

ENV APP_ENV=${APP_ENV} \
    SERVER_PORT=${SERVER_PORT} \
    APP_FRONTEND_URL=${APP_FRONTEND_URL:-https://travelmedicineadvisory.com} \
    APP_HOST=${APP_HOST:-0.0.0.0} \
    SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://db:5432/tmag} \
    SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-tmag} \
    SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-changeme} \
    SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO:-update} \
    JWT_SECRET=${JWT_SECRET} \
    APP_API_KEY=${APP_API_KEY} \
    SPRING_MAIL_HOST=${SPRING_MAIL_HOST:-smtp.gmail.com} \
    SPRING_MAIL_PORT=${SPRING_MAIL_PORT:-587} \
    SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:-} \
    SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:-} \
    REDIS_HOST=${REDIS_HOST:-redis} \
    REDIS_PORT=${REDIS_PORT:-6379} \
    APP_STORAGE_PATH=/app/storage \
    APP_STORAGE_BASE_URL=${APP_STORAGE_BASE_URL:-https://storage.travelmedicineadvisory.com} \
    FLUTTERWAVE_PUBLIC_KEY=${FLUTTERWAVE_PUBLIC_KEY:-} \
    FLUTTERWAVE_SECRET_KEY=${FLUTTERWAVE_SECRET_KEY:-} \
    FLUTTERWAVE_ENCRYPTION_KEY=${FLUTTERWAVE_ENCRYPTION_KEY:-} \
    FLUTTERWAVE_CALLBACK_URL=${FLUTTERWAVE_CALLBACK_URL:-https://travelmedicineadvisory.com/payment/callback} \
    FLUTTERWAVE_WEBHOOK_URL=${FLUTTERWAVE_WEBHOOK_URL:-https://travelmedicineadvisory.com/api/v1/payments/webhook}

RUN mkdir -p /app/storage/upload

COPY --from=build /app/target/Server-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]