### GET request to example server

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json
X-Api-Key: 26aeb674-1ae8-11f1-b69e-2b73bbf41615

{
    "username": "dikewisdom",
    "password": "password",
    "first_name": "Dike Wisdom",
    "last_name": "User",
    "phone": "08099997777",
    "email": "dikewisdom787@gmail.com"
}