### GET request to example server

###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "username": "dikewisdom2",
    "password": "password",
    "first_name": "Dike Thomas",
    "last_name": "User",
    "email": "dikewisdom770@gmail.com"
}