CREATE TABLE abuse_flags
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    type        VARCHAR(255),
    description TEXT,
    severity    VARCHAR(255),
    resolved    BOOLEAN,
    resolved_by BIGINT,
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    user_id     BIGINT,
    CONSTRAINT pk_abuse_flags PRIMARY KEY (id)
);

CREATE TABLE ai_request_logs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted_at         TIMESTAMP WITHOUT TIME ZONE,
    destination        VARCHAR(255),
    prompt_summary     TEXT,
    output_summary     TEXT,
    tokens_used        INTEGER,
    processing_time_ms BIGINT,
    status             VARCHAR(255),
    error_message      TEXT,
    risk_level         VARCHAR(255),
    model_used         VARCHAR(255),
    credit_consumed    DECIMAL(10, 2),
    company_id         BIGINT,
    user_id            BIGINT,
    CONSTRAINT pk_ai_request_logs PRIMARY KEY (id)
);

CREATE TABLE attachments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    file_name    VARCHAR(255),
    file_size    BIGINT,
    content_type VARCHAR(255),
    storage_path VARCHAR(255),
    model_id     BIGINT,
    model_name   VARCHAR(255),
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

CREATE TABLE blog_posts
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    title             VARCHAR(255),
    slug              VARCHAR(255),
    excerpt           TEXT,
    content           TEXT,
    category          VARCHAR(255),
    read_time         INTEGER,
    is_published      BOOLEAN,
    published_at      TIMESTAMP WITHOUT TIME ZONE,
    user_id           BIGINT,
    featured_image_id BIGINT,
    CONSTRAINT pk_blog_posts PRIMARY KEY (id)
);

CREATE TABLE companies
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    name             VARCHAR(255),
    industry         VARCHAR(255),
    total_credits    INTEGER,
    used_credits     INTEGER,
    employee_count   INTEGER,
    plan             VARCHAR(255),
    company_code     VARCHAR(255),
    tier             VARCHAR(255),
    contract_renewal TIMESTAMP WITHOUT TIME ZONE,
    website          VARCHAR(255),
    address          VARCHAR(255),
    contact_email    VARCHAR(255),
    contact_phone    VARCHAR(255),
    billing_currency VARCHAR(255),
    billing_status   VARCHAR(255),
    logo_id          BIGINT,
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

CREATE TABLE company_api_keys
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    key_name     VARCHAR(255)                            NOT NULL,
    key_hash     VARCHAR(255)                            NOT NULL,
    key_prefix   VARCHAR(255)                            NOT NULL,
    company_id   BIGINT                                  NOT NULL,
    status       VARCHAR(255),
    last_used_at TIMESTAMP WITHOUT TIME ZONE,
    expires_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_company_api_keys PRIMARY KEY (id)
);

CREATE TABLE company_settings
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    company_id    BIGINT                                  NOT NULL,
    setting_key   VARCHAR(255)                            NOT NULL,
    setting_value TEXT,
    setting_type  VARCHAR(255),
    CONSTRAINT pk_company_settings PRIMARY KEY (id)
);

CREATE TABLE company_users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    role              VARCHAR(255),
    credits_allocated INTEGER                                 NOT NULL,
    credits_used      INTEGER                                 NOT NULL,
    company_id        BIGINT,
    user_id           BIGINT,
    CONSTRAINT pk_company_users PRIMARY KEY (id)
);

CREATE TABLE contacts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    subject      VARCHAR(255)                            NOT NULL,
    message      TEXT                                    NOT NULL,
    inquiry_type VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    ip_address   VARCHAR(255),
    user_agent   VARCHAR(255),
    CONSTRAINT pk_contacts PRIMARY KEY (id)
);

CREATE TABLE countries
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    name             VARCHAR(255)                            NOT NULL,
    code             VARCHAR(255)                            NOT NULL,
    region           VARCHAR(255),
    continent        VARCHAR(255),
    risk_level       VARCHAR(255),
    visa_info        TEXT,
    currency         VARCHAR(255),
    language         VARCHAR(255),
    timezone         VARCHAR(255),
    health_advisory  TEXT,
    travel_advisory  TEXT,
    emergency_number VARCHAR(255),
    is_active        BOOLEAN,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

CREATE TABLE country_accommodations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    city                VARCHAR(255),
    type                VARCHAR(255),
    name                VARCHAR(255),
    avg_price_per_night DECIMAL(10, 2),
    currency            VARCHAR(255),
    rating              DOUBLE PRECISION,
    source_url          TEXT,
    last_updated_at     TIMESTAMP WITHOUT TIME ZONE,
    country_id          BIGINT,
    CONSTRAINT pk_country_accommodations PRIMARY KEY (id)
);

CREATE TABLE country_health_alerts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    title       VARCHAR(255),
    description TEXT,
    severity    VARCHAR(255),
    alert_type  VARCHAR(255),
    source      VARCHAR(255),
    source_url  TEXT,
    starts_at   TIMESTAMP WITHOUT TIME ZONE,
    expires_at  TIMESTAMP WITHOUT TIME ZONE,
    is_active   BOOLEAN,
    country_id  BIGINT,
    CONSTRAINT pk_country_health_alerts PRIMARY KEY (id)
);

CREATE TABLE credit_pricing
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    deleted_at                TIMESTAMP WITHOUT TIME ZONE,
    currency                  VARCHAR(255)                            NOT NULL,
    currency_symbol           VARCHAR(255)                            NOT NULL,
    price_per_credit          DECIMAL(10, 2)                          NOT NULL,
    min_credits               INTEGER                                 NOT NULL,
    max_credits               INTEGER                                 NOT NULL,
    discount_tier_1_threshold DECIMAL(12, 2),
    discount_tier_1_amount    DECIMAL(10, 2),
    discount_tier_2_threshold DECIMAL(12, 2),
    discount_tier_2_amount    DECIMAL(10, 2),
    discount_tier_3_threshold DECIMAL(12, 2),
    discount_tier_3_amount    DECIMAL(10, 2),
    is_active                 BOOLEAN                                 NOT NULL,
    display_order             INTEGER,
    CONSTRAINT pk_credit_pricing PRIMARY KEY (id)
);

CREATE TABLE credit_purchases
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted_at         TIMESTAMP WITHOUT TIME ZONE,
    tx_ref             VARCHAR(255)                            NOT NULL,
    flw_ref            VARCHAR(255),
    user_id            BIGINT                                  NOT NULL,
    company_id         BIGINT,
    credits_purchased  INTEGER                                 NOT NULL,
    currency           VARCHAR(255)                            NOT NULL,
    currency_symbol    VARCHAR(255),
    price_per_credit   DECIMAL(10, 2)                          NOT NULL,
    amount             DECIMAL(10, 2)                          NOT NULL,
    amount_paid        DECIMAL(10, 2),
    status             VARCHAR(255)                            NOT NULL,
    flutterwave_status VARCHAR(255),
    metadata           TEXT,
    paid_at            TIMESTAMP WITHOUT TIME ZONE,
    failed_at          TIMESTAMP WITHOUT TIME ZONE,
    failed_reason      VARCHAR(255),
    CONSTRAINT pk_credit_purchases PRIMARY KEY (id)
);

CREATE TABLE credit_requests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    credits_requested INTEGER,
    reason            VARCHAR(255),
    status            VARCHAR(255),
    submitted_at      TIMESTAMP WITHOUT TIME ZONE,
    company_id        BIGINT,
    employee_id       BIGINT,
    CONSTRAINT pk_credit_requests PRIMARY KEY (id)
);

CREATE TABLE credits
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    amount        INTEGER,
    type          VARCHAR(255),
    reference     VARCHAR(255),
    balance_after INTEGER,
    company_id    BIGINT,
    user_id       BIGINT,
    CONSTRAINT pk_credits PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    name              VARCHAR(255),
    email             VARCHAR(255),
    department        VARCHAR(255),
    credits_used      INTEGER,
    credits_allocated INTEGER,
    status            VARCHAR(255),
    plans_generated   INTEGER,
    company_id        BIGINT,
    user_id           BIGINT,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE faq_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    question   TEXT                                    NOT NULL,
    answer     TEXT                                    NOT NULL,
    category   VARCHAR(255),
    position   INTEGER,
    is_active  BOOLEAN,
    CONSTRAINT pk_faq_items PRIMARY KEY (id)
);

CREATE TABLE health_profiles
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    deleted_at              TIMESTAMP WITHOUT TIME ZONE,
    conditions              TEXT,
    medications             TEXT,
    allergies               TEXT,
    blood_type              VARCHAR(255),
    emergency_contact_name  VARCHAR(255),
    emergency_contact_phone VARCHAR(255),
    user_id                 BIGINT,
    CONSTRAINT pk_health_profiles PRIMARY KEY (id)
);

CREATE TABLE invoices
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    amount         DECIMAL(10, 2),
    currency       VARCHAR(255),
    status         VARCHAR(255),
    description    TEXT,
    issued_at      TIMESTAMP WITHOUT TIME ZONE,
    due_date       TIMESTAMP WITHOUT TIME ZONE,
    paid_at        TIMESTAMP WITHOUT TIME ZONE,
    payment_method VARCHAR(255),
    company_id     BIGINT,
    user_id        BIGINT,
    CONSTRAINT pk_invoices PRIMARY KEY (id)
);

CREATE TABLE newsletter_subscribers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255)                            NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_newsletter_subscribers PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    title      VARCHAR(255),
    message    TEXT,
    type       VARCHAR(255),
    is_read    BOOLEAN,
    link       VARCHAR(255),
    user_id    BIGINT,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE onboarding_question_categories
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    deleted_at           TIMESTAMP WITHOUT TIME ZONE,
    category_key         VARCHAR(255)                            NOT NULL,
    category_name        VARCHAR(255)                            NOT NULL,
    category_icon        VARCHAR(255),
    category_description TEXT,
    display_order        INTEGER,
    is_optional          BOOLEAN,
    questions            TEXT,
    CONSTRAINT pk_onboarding_question_categories PRIMARY KEY (id)
);

CREATE TABLE permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(255),
    description   VARCHAR(255),
    resource_type VARCHAR(255),
    action        VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE plan_usage_ledgers
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    action         VARCHAR(255),
    ip_address     VARCHAR(255),
    user_agent     VARCHAR(255),
    travel_plan_id BIGINT,
    user_id        BIGINT,
    CONSTRAINT pk_plan_usage_ledgers PRIMARY KEY (id)
);

CREATE TABLE resource_access
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    role_id       VARCHAR(255),
    member_id     BIGINT,
    resource_type VARCHAR(255),
    resource_id   VARCHAR(255),
    access_type   VARCHAR(255),
    CONSTRAINT pk_resource_access PRIMARY KEY (id)
);

CREATE TABLE resource_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    resource_type VARCHAR(255),
    resource_id   VARCHAR(255),
    user_id       BIGINT,
    role_id       BIGINT,
    action        VARCHAR(255),
    default_scope VARCHAR(255),
    permission_id BIGINT,
    CONSTRAINT pk_resource_permissions PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    role_id       BIGINT,
    permission_id BIGINT,
    CONSTRAINT pk_role_permissions PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(255)                            NOT NULL,
    permissions TEXT,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE system_logs
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    level      VARCHAR(255),
    message    TEXT,
    source     VARCHAR(255),
    details    TEXT,
    CONSTRAINT pk_system_logs PRIMARY KEY (id)
);

CREATE TABLE system_settings
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    setting_key   VARCHAR(255)                            NOT NULL,
    setting_value TEXT,
    setting_type  VARCHAR(255),
    setting_group VARCHAR(255),
    label         VARCHAR(255),
    description   TEXT,
    is_public     BOOLEAN,
    CONSTRAINT pk_system_settings PRIMARY KEY (id)
);

CREATE TABLE translations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    setting_key VARCHAR(255),
    value       TEXT,
    model       VARCHAR(255),
    model_id    BIGINT,
    language    VARCHAR(255),
    CONSTRAINT pk_translations PRIMARY KEY (id)
);

CREATE TABLE travel_plans
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    deleted_at             TIMESTAMP WITHOUT TIME ZONE,
    destination            VARCHAR(255),
    country                VARCHAR(255),
    duration               INTEGER,
    purpose                VARCHAR(255),
    risk_score             INTEGER,
    status                 VARCHAR(255),
    medical_considerations TEXT,
    vaccinations           TEXT,
    health_alerts          TEXT,
    safety_advisories      TEXT,
    medications            TEXT,
    water_food             TEXT,
    emergency_contacts     TEXT,
    company_id             BIGINT,
    employee_id            BIGINT,
    user_id                BIGINT,
    CONSTRAINT pk_travel_plans PRIMARY KEY (id)
);

CREATE TABLE user_onboardings
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    deleted_at              TIMESTAMP WITHOUT TIME ZONE,
    user_type               VARCHAR(255),
    nationality             VARCHAR(255),
    company_code            VARCHAR(255),
    completed_at            TIMESTAMP WITHOUT TIME ZONE,
    responses_json          TEXT,
    questionnaire_completed BOOLEAN,
    user_id                 BIGINT,
    CONSTRAINT pk_user_onboardings PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    deleted_at                TIMESTAMP WITHOUT TIME ZONE,
    first_name                VARCHAR(255),
    last_name                 VARCHAR(255),
    name                      VARCHAR(255),
    username                  VARCHAR(255),
    phone                     VARCHAR(255),
    email                     VARCHAR(255)                            NOT NULL,
    password                  VARCHAR(255),
    onboarding_stage          INTEGER,
    onboarded                 BOOLEAN                                 NOT NULL,
    is_verified               BOOLEAN,
    is_active                 BOOLEAN,
    verification_token        VARCHAR(255),
    verification_token_expiry TIMESTAMP WITHOUT TIME ZONE,
    reset_token               VARCHAR(255),
    reset_token_expiry        TIMESTAMP WITHOUT TIME ZONE,
    invitation_token          VARCHAR(255),
    invitation_token_expiry   TIMESTAMP WITHOUT TIME ZONE,
    must_change_password      BOOLEAN,
    last_login                TIMESTAMP WITHOUT TIME ZONE,
    avatar_url                VARCHAR(255),
    credits                   INTEGER,
    type                      VARCHAR(255),
    provider                  VARCHAR(255),
    provider_id               VARCHAR(255),
    billing_currency          VARCHAR(255),
    role_id                   BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE company_settings
    ADD CONSTRAINT uc_ad9da353099f5544d5f132b3d UNIQUE (company_id, setting_key);

ALTER TABLE blog_posts
    ADD CONSTRAINT uc_blog_posts_featured_image UNIQUE (featured_image_id);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_company_code UNIQUE (company_code);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_logo UNIQUE (logo_id);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_code UNIQUE (code);

ALTER TABLE credit_pricing
    ADD CONSTRAINT uc_credit_pricing_currency UNIQUE (currency);

ALTER TABLE credit_purchases
    ADD CONSTRAINT uc_credit_purchases_tx_ref UNIQUE (tx_ref);

ALTER TABLE newsletter_subscribers
    ADD CONSTRAINT uc_newsletter_subscribers_email UNIQUE (email);

ALTER TABLE onboarding_question_categories
    ADD CONSTRAINT uc_onboarding_question_categories_category_key UNIQUE (category_key);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE system_settings
    ADD CONSTRAINT uc_system_settings_setting_key UNIQUE (setting_key);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE abuse_flags
    ADD CONSTRAINT FK_ABUSE_FLAGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE ai_request_logs
    ADD CONSTRAINT FK_AI_REQUEST_LOGS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE ai_request_logs
    ADD CONSTRAINT FK_AI_REQUEST_LOGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE blog_posts
    ADD CONSTRAINT FK_BLOG_POSTS_ON_FEATURED_IMAGE FOREIGN KEY (featured_image_id) REFERENCES attachments (id);

ALTER TABLE blog_posts
    ADD CONSTRAINT FK_BLOG_POSTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE companies
    ADD CONSTRAINT FK_COMPANIES_ON_LOGO FOREIGN KEY (logo_id) REFERENCES attachments (id);

ALTER TABLE company_api_keys
    ADD CONSTRAINT FK_COMPANY_API_KEYS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE company_settings
    ADD CONSTRAINT FK_COMPANY_SETTINGS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE company_users
    ADD CONSTRAINT FK_COMPANY_USERS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE company_users
    ADD CONSTRAINT FK_COMPANY_USERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE country_accommodations
    ADD CONSTRAINT FK_COUNTRY_ACCOMMODATIONS_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE country_health_alerts
    ADD CONSTRAINT FK_COUNTRY_HEALTH_ALERTS_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);

ALTER TABLE credits
    ADD CONSTRAINT FK_CREDITS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE credits
    ADD CONSTRAINT FK_CREDITS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE credit_purchases
    ADD CONSTRAINT FK_CREDIT_PURCHASES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE credit_requests
    ADD CONSTRAINT FK_CREDIT_REQUESTS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE credit_requests
    ADD CONSTRAINT FK_CREDIT_REQUESTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE health_profiles
    ADD CONSTRAINT FK_HEALTH_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE invoices
    ADD CONSTRAINT FK_INVOICES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE plan_usage_ledgers
    ADD CONSTRAINT FK_PLAN_USAGE_LEDGERS_ON_TRAVEL_PLAN FOREIGN KEY (travel_plan_id) REFERENCES travel_plans (id);

ALTER TABLE plan_usage_ledgers
    ADD CONSTRAINT FK_PLAN_USAGE_LEDGERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE resource_permissions
    ADD CONSTRAINT FK_RESOURCE_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE resource_permissions
    ADD CONSTRAINT FK_RESOURCE_PERMISSIONS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSIONS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT FK_ROLE_PERMISSIONS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE travel_plans
    ADD CONSTRAINT FK_TRAVEL_PLANS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE travel_plans
    ADD CONSTRAINT FK_TRAVEL_PLANS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE travel_plans
    ADD CONSTRAINT FK_TRAVEL_PLANS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_onboardings
    ADD CONSTRAINT FK_USER_ONBOARDINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);