CREATE TABLE draft_plans
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    title          VARCHAR(255),
    country        VARCHAR(255),
    answers_json   TEXT,
    category_index INTEGER,
    user_id        BIGINT,
    CONSTRAINT pk_draft_plans PRIMARY KEY (id)
);

ALTER TABLE draft_plans
    ADD CONSTRAINT FK_DRAFT_PLANS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);