ALTER TABLE credit_purchases
    ADD COLUMN IF NOT EXISTS affiliate_referral_code VARCHAR(40),
    ADD COLUMN IF NOT EXISTS affiliate_discount_rate DECIMAL(5, 2),
    ADD COLUMN IF NOT EXISTS affiliate_discount_amount DECIMAL(10, 2);

CREATE TABLE IF NOT EXISTS affiliate_profiles
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    deleted_at              TIMESTAMP WITHOUT TIME ZONE,
    user_id                 BIGINT                                  NOT NULL,
    referral_code           VARCHAR(40)                             NOT NULL,
    commission_rate         DECIMAL(5, 2)                           NOT NULL DEFAULT 10.00,
    discount_rate           DECIMAL(5, 2)                           NOT NULL DEFAULT 2.00,
    total_clicks            INTEGER                                 NOT NULL DEFAULT 0,
    total_conversions       INTEGER                                 NOT NULL DEFAULT 0,
    total_commission_earned DECIMAL(12, 2)                          NOT NULL DEFAULT 0.00,
    total_paid_out          DECIMAL(12, 2)                          NOT NULL DEFAULT 0.00,
    pending_commission      DECIMAL(12, 2)                          NOT NULL DEFAULT 0.00,
    status                  VARCHAR(20)                             NOT NULL DEFAULT 'active',
    CONSTRAINT pk_affiliate_profiles PRIMARY KEY (id),
    CONSTRAINT uk_affiliate_profiles_user UNIQUE (user_id),
    CONSTRAINT uk_affiliate_profiles_referral_code UNIQUE (referral_code),
    CONSTRAINT fk_affiliate_profiles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS affiliate_referral_links
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    affiliate_id      BIGINT                                  NOT NULL,
    credit_plan_id    BIGINT,
    campaign          VARCHAR(120)                            NOT NULL,
    destination_url   TEXT                                    NOT NULL,
    short_code        VARCHAR(40)                             NOT NULL,
    clicks            INTEGER                                 NOT NULL DEFAULT 0,
    conversions       INTEGER                                 NOT NULL DEFAULT 0,
    commission_earned DECIMAL(12, 2)                          NOT NULL DEFAULT 0.00,
    is_active         BOOLEAN                                 NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_affiliate_referral_links PRIMARY KEY (id),
    CONSTRAINT uk_affiliate_referral_links_short_code UNIQUE (short_code),
    CONSTRAINT fk_affiliate_referral_links_affiliate FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles (id),
    CONSTRAINT fk_affiliate_referral_links_credit_plan FOREIGN KEY (credit_plan_id) REFERENCES user_credit_plans (id)
);

CREATE TABLE IF NOT EXISTS affiliate_referrals
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    affiliate_id     BIGINT                                  NOT NULL,
    referral_link_id BIGINT,
    referred_user_id BIGINT                                  NOT NULL,
    referral_code    VARCHAR(40)                             NOT NULL,
    status           VARCHAR(20)                             NOT NULL DEFAULT 'active',
    first_click_at   TIMESTAMP WITHOUT TIME ZONE,
    converted_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_affiliate_referrals PRIMARY KEY (id),
    CONSTRAINT uk_affiliate_referrals_referred_user UNIQUE (referred_user_id),
    CONSTRAINT fk_affiliate_referrals_affiliate FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles (id),
    CONSTRAINT fk_affiliate_referrals_link FOREIGN KEY (referral_link_id) REFERENCES affiliate_referral_links (id),
    CONSTRAINT fk_affiliate_referrals_user FOREIGN KEY (referred_user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS affiliate_commissions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    affiliate_id     BIGINT                                  NOT NULL,
    referral_link_id BIGINT,
    referred_user_id BIGINT,
    amount           DECIMAL(12, 2)                          NOT NULL,
    base_amount      DECIMAL(12, 2)                          NOT NULL,
    rate             DECIMAL(5, 2)                           NOT NULL,
    status           VARCHAR(20)                             NOT NULL DEFAULT 'approved',
    customer_email   VARCHAR(255),
    reference_type   VARCHAR(60)                             NOT NULL,
    reference_id     BIGINT                                  NOT NULL,
    paid_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_affiliate_commissions PRIMARY KEY (id),
    CONSTRAINT fk_affiliate_commissions_affiliate FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles (id),
    CONSTRAINT fk_affiliate_commissions_link FOREIGN KEY (referral_link_id) REFERENCES affiliate_referral_links (id),
    CONSTRAINT fk_affiliate_commissions_user FOREIGN KEY (referred_user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS affiliate_payouts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    affiliate_id    BIGINT                                  NOT NULL,
    amount          DECIMAL(12, 2)                          NOT NULL,
    payment_method  VARCHAR(80)                             NOT NULL,
    payment_details TEXT                                    NOT NULL,
    status          VARCHAR(20)                             NOT NULL DEFAULT 'pending',
    notes           TEXT,
    requested_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_affiliate_payouts PRIMARY KEY (id),
    CONSTRAINT fk_affiliate_payouts_affiliate FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles (id)
);

CREATE TABLE IF NOT EXISTS affiliate_clicks
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    affiliate_id     BIGINT                                  NOT NULL,
    referral_link_id BIGINT                                  NOT NULL,
    ip_address       VARCHAR(80),
    user_agent       TEXT,
    CONSTRAINT pk_affiliate_clicks PRIMARY KEY (id),
    CONSTRAINT fk_affiliate_clicks_affiliate FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles (id),
    CONSTRAINT fk_affiliate_clicks_link FOREIGN KEY (referral_link_id) REFERENCES affiliate_referral_links (id)
);

CREATE INDEX IF NOT EXISTS idx_affiliate_profiles_user ON affiliate_profiles (user_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_profiles_referral_code ON affiliate_profiles (referral_code);
CREATE INDEX IF NOT EXISTS idx_affiliate_profiles_status ON affiliate_profiles (status);
CREATE INDEX IF NOT EXISTS idx_affiliate_referral_links_affiliate ON affiliate_referral_links (affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_referral_links_short_code ON affiliate_referral_links (short_code);
CREATE INDEX IF NOT EXISTS idx_affiliate_referral_links_plan ON affiliate_referral_links (credit_plan_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_referrals_affiliate ON affiliate_referrals (affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_referrals_link ON affiliate_referrals (referral_link_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_referrals_referred_user ON affiliate_referrals (referred_user_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_commissions_affiliate ON affiliate_commissions (affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_commissions_link ON affiliate_commissions (referral_link_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_commissions_referred_user ON affiliate_commissions (referred_user_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_commissions_reference ON affiliate_commissions (reference_type, reference_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_commissions_status ON affiliate_commissions (status);
CREATE INDEX IF NOT EXISTS idx_affiliate_payouts_affiliate ON affiliate_payouts (affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_payouts_status ON affiliate_payouts (status);
CREATE INDEX IF NOT EXISTS idx_affiliate_payouts_requested ON affiliate_payouts (requested_at);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_affiliate ON affiliate_clicks (affiliate_id, created_at);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_link ON affiliate_clicks (referral_link_id, created_at);

INSERT INTO roles (created_at, updated_at, name, permissions)
SELECT CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Affiliate', '[]'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'Affiliate');

INSERT INTO permissions (created_at, updated_at, name, description, resource_type, action)
SELECT CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'affiliate:' || actions.action_value, 'Can ' || actions.action_value || ' affiliate', 'affiliate', actions.action_value
FROM (VALUES ('create'), ('read'), ('update'), ('delete'), ('list')) AS actions(action_value)
WHERE NOT EXISTS (SELECT 1 FROM permissions p WHERE p.name = 'affiliate:' || actions.action_value);

INSERT INTO role_permissions (created_at, updated_at, role_id, permission_id)
SELECT CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, r.id, p.id
FROM roles r
JOIN permissions p ON p.name IN ('affiliate:create', 'affiliate:read', 'affiliate:update', 'affiliate:list', 'profile:read', 'profile:update', 'pricing_plan:read', 'pricing_plan:list')
WHERE r.name = 'Affiliate'
  AND NOT EXISTS (
      SELECT 1 FROM role_permissions rp WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );

INSERT INTO role_permissions (created_at, updated_at, role_id, permission_id)
SELECT CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, r.id, p.id
FROM roles r
JOIN permissions p ON p.name LIKE 'affiliate:%'
WHERE r.name IN ('SuperAdmin', 'Administrator')
  AND NOT EXISTS (
      SELECT 1 FROM role_permissions rp WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
