CREATE TABLE company_plans
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                          TIMESTAMP WITHOUT TIME ZONE,
    updated_at                          TIMESTAMP WITHOUT TIME ZONE,
    deleted_at                          TIMESTAMP WITHOUT TIME ZONE,
    code                                VARCHAR(255)                            NOT NULL,
    display_name                        VARCHAR(255)                            NOT NULL,
    signup_credits                      INTEGER                                 NOT NULL,
    max_employees                       INTEGER                                 NOT NULL,
    custom_support_enabled              BOOLEAN                                 NOT NULL,
    api_access_enabled                  BOOLEAN                                 NOT NULL,
    multiple_admin_accounts_enabled     BOOLEAN                                 NOT NULL,
    over_ten_thousand_employees_enabled BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_company_plans PRIMARY KEY (id)
);

ALTER TABLE companies
    ADD active_plan_id BIGINT;

ALTER TABLE company_plans
    ADD CONSTRAINT uc_company_plans_code UNIQUE (code);

ALTER TABLE companies
    ADD CONSTRAINT FK_COMPANIES_ON_ACTIVE_PLAN FOREIGN KEY (active_plan_id) REFERENCES company_plans (id);