CREATE TABLE company_onboarding_requests
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted_at         TIMESTAMP WITHOUT TIME ZONE,
    company_name       VARCHAR(255)                            NOT NULL,
    industry           VARCHAR(255),
    contact_email      VARCHAR(255)                            NOT NULL,
    contact_phone      VARCHAR(255),
    website            VARCHAR(255),
    billing_currency   VARCHAR(255)                            NOT NULL,
    selected_plan_code VARCHAR(255)                            NOT NULL,
    sample_request     TEXT,
    team_members       TEXT                                    NOT NULL,
    tx_ref             VARCHAR(255),
    payment_status     VARCHAR(255)                            NOT NULL,
    payment_amount     DECIMAL,
    payment_currency   VARCHAR(255),
    flw_ref            VARCHAR(255),
    paid_at            TIMESTAMP WITHOUT TIME ZONE,
    status             VARCHAR(255)                            NOT NULL,
    rejection_reason   TEXT,
    reviewed_by        VARCHAR(255),
    reviewed_at        TIMESTAMP WITHOUT TIME ZONE,
    created_company_id BIGINT,
    CONSTRAINT pk_company_onboarding_requests PRIMARY KEY (id)
);

ALTER TABLE company_plans
    ADD price_eur DECIMAL;

ALTER TABLE company_plans
    ADD price_gbp DECIMAL;

ALTER TABLE company_plans
    ADD price_ngn DECIMAL;

ALTER TABLE company_plans
    ADD price_usd DECIMAL;

ALTER TABLE company_plans
    ALTER COLUMN price_ngn SET NOT NULL;

ALTER TABLE company_plans
    ALTER COLUMN price_usd SET NOT NULL;

ALTER TABLE company_onboarding_requests
    ADD CONSTRAINT uc_company_onboarding_requests_tx_ref UNIQUE (tx_ref);