ALTER TABLE travel_plans
  ADD COLUMN IF NOT EXISTS plan_tier VARCHAR(20) DEFAULT 'FREE',
  ADD COLUMN IF NOT EXISTS doctor_validation_status VARCHAR(20) DEFAULT 'NOT_REQUIRED',
  ADD COLUMN IF NOT EXISTS validated_by_id BIGINT REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS validated_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT;

ALTER TABLE generated_plans
  ADD COLUMN IF NOT EXISTS signed_pdf_url VARCHAR(500),
  ADD COLUMN IF NOT EXISTS is_signed BOOLEAN DEFAULT FALSE;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS medical_license_number VARCHAR(100),
  ADD COLUMN IF NOT EXISTS signature_url VARCHAR(500),
  ADD COLUMN IF NOT EXISTS doctor_application_status VARCHAR(20) DEFAULT 'NONE';
