CREATE TABLE user_credit_plans
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    code           VARCHAR(255)                            NOT NULL,
    display_name   VARCHAR(255)                            NOT NULL,
    base_price_usd DECIMAL(10, 2)                          NOT NULL,
    description    TEXT,
    is_default     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_credit_plans PRIMARY KEY (id)
);

ALTER TABLE companies
    ADD credit_plan_id BIGINT;

ALTER TABLE users
    ADD user_credit_plan_id BIGINT;

ALTER TABLE user_credit_plans
    ADD CONSTRAINT uc_user_credit_plans_code UNIQUE (code);

ALTER TABLE companies
    ADD CONSTRAINT FK_COMPANIES_ON_CREDIT_PLAN FOREIGN KEY (credit_plan_id) REFERENCES user_credit_plans (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_USER_CREDIT_PLAN FOREIGN KEY (user_credit_plan_id) REFERENCES user_credit_plans (id);