ALTER TABLE travel_requests
    DROP CONSTRAINT fkcs3gys6ke30muayb6wisrs5jo;

ALTER TABLE travel_requests
    DROP CONSTRAINT fkhi0yp6pmir6msshe80hkj3x4u;

CREATE TABLE contacts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    subject      VARCHAR(255)                            NOT NULL,
    message      TEXT                                    NOT NULL,
    inquiry_type VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    ip_address   VARCHAR(255),
    user_agent   VARCHAR(255),
    CONSTRAINT pk_contacts PRIMARY KEY (id)
);

CREATE TABLE credit_requests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    credits_requested INTEGER,
    reason            VARCHAR(255),
    status            VARCHAR(255),
    submitted_at      TIMESTAMP WITHOUT TIME ZONE,
    company_id        BIGINT,
    employee_id       BIGINT,
    CONSTRAINT pk_credit_requests PRIMARY KEY (id)
);

CREATE TABLE ebook_cart_items
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    user_id          BIGINT                                  NOT NULL,
    ebook_id         BIGINT                                  NOT NULL,
    ebook_version_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_ebook_cart_items PRIMARY KEY (id)
);

CREATE TABLE ebook_orders
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted_at         TIMESTAMP WITHOUT TIME ZONE,
    tx_ref             VARCHAR(255)                            NOT NULL,
    flw_ref            VARCHAR(255),
    user_id            BIGINT,
    guest_email        VARCHAR(255),
    guest_name         VARCHAR(255),
    guest_phone        VARCHAR(255),
    ebook_id           BIGINT                                  NOT NULL,
    ebook_version_id   BIGINT                                  NOT NULL,
    amount             DECIMAL(10, 2)                          NOT NULL,
    amount_paid        DECIMAL(10, 2),
    currency           VARCHAR(3)                              NOT NULL,
    currency_symbol    VARCHAR(10),
    status             VARCHAR(255)                            NOT NULL,
    flutterwave_status VARCHAR(255),
    paid_at            TIMESTAMP WITHOUT TIME ZONE,
    failed_at          TIMESTAMP WITHOUT TIME ZONE,
    failed_reason      VARCHAR(255),
    email_sent         BOOLEAN,
    email_sent_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ebook_orders PRIMARY KEY (id)
);

CREATE TABLE ebook_versions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    ebook_id        BIGINT                                  NOT NULL,
    label           VARCHAR(255)                            NOT NULL,
    country_code    VARCHAR(255),
    country_name    VARCHAR(255),
    region          VARCHAR(255),
    price           DECIMAL(10, 2)                          NOT NULL,
    currency        VARCHAR(3)                              NOT NULL,
    currency_symbol VARCHAR(10),
    file_url        VARCHAR(255),
    file_key        VARCHAR(255),
    file_size_mb    DECIMAL(6, 2),
    is_active       BOOLEAN                                 NOT NULL,
    sort_order      INTEGER,
    CONSTRAINT pk_ebook_versions PRIMARY KEY (id)
);

CREATE TABLE ebooks
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    title             VARCHAR(255)                            NOT NULL,
    slug              VARCHAR(255)                            NOT NULL,
    description       TEXT,
    short_description VARCHAR(255),
    author            VARCHAR(255)                            NOT NULL,
    author_bio        TEXT,
    cover_url         VARCHAR(255),
    preview_url       VARCHAR(255),
    page_count        INTEGER,
    published_year    INTEGER,
    isbn              VARCHAR(255),
    is_active         BOOLEAN                                 NOT NULL,
    is_featured       BOOLEAN                                 NOT NULL,
    sort_order        INTEGER,
    CONSTRAINT pk_ebooks PRIMARY KEY (id)
);

CREATE TABLE generated_plans
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    deleted_at         TIMESTAMP WITHOUT TIME ZONE,
    travel_plan_id     BIGINT,
    user_id            BIGINT,
    company_id         BIGINT,
    destination        VARCHAR(255),
    duration           INTEGER,
    purpose            VARCHAR(255),
    risk_score         INTEGER,
    status             VARCHAR(255),
    provider           VARCHAR(255),
    model_used         VARCHAR(255),
    tokens_used        INTEGER,
    processing_time_ms BIGINT,
    error_message      TEXT,
    plan_json          TEXT,
    CONSTRAINT pk_generated_plans PRIMARY KEY (id)
);

CREATE TABLE newsletter_subscribers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255)                            NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_newsletter_subscribers PRIMARY KEY (id)
);

CREATE TABLE plan_generation_contexts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    title            VARCHAR(255),
    source_type      VARCHAR(255),
    file_name        VARCHAR(255),
    content_type     VARCHAR(255),
    storage_path     VARCHAR(255),
    raw_text         TEXT,
    synthesized_text TEXT,
    active           BOOLEAN,
    CONSTRAINT pk_plan_generation_contexts PRIMARY KEY (id)
);

CREATE TABLE travel_plan_questionnaires
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    responses_json TEXT,
    source         VARCHAR(255),
    travel_plan_id BIGINT,
    user_id        BIGINT,
    employee_id    BIGINT,
    company_id     BIGINT,
    CONSTRAINT pk_travel_plan_questionnaires PRIMARY KEY (id)
);

ALTER TABLE travel_plans
    ADD trip_details_json TEXT;

ALTER TABLE travel_plans
    ADD trip_type VARCHAR(255);

ALTER TABLE ebooks
    ADD CONSTRAINT uc_ebooks_slug UNIQUE (slug);

ALTER TABLE generated_plans
    ADD CONSTRAINT uc_generated_plans_travel_plan UNIQUE (travel_plan_id);

ALTER TABLE newsletter_subscribers
    ADD CONSTRAINT uc_newsletter_subscribers_email UNIQUE (email);

ALTER TABLE travel_plan_questionnaires
    ADD CONSTRAINT uc_travel_plan_questionnaires_travel_plan UNIQUE (travel_plan_id);

ALTER TABLE credit_requests
    ADD CONSTRAINT FK_CREDIT_REQUESTS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE credit_requests
    ADD CONSTRAINT FK_CREDIT_REQUESTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE ebook_cart_items
    ADD CONSTRAINT FK_EBOOK_CART_ITEMS_ON_EBOOK FOREIGN KEY (ebook_id) REFERENCES ebooks (id);

ALTER TABLE ebook_cart_items
    ADD CONSTRAINT FK_EBOOK_CART_ITEMS_ON_EBOOK_VERSION FOREIGN KEY (ebook_version_id) REFERENCES ebook_versions (id);

ALTER TABLE ebook_cart_items
    ADD CONSTRAINT FK_EBOOK_CART_ITEMS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE ebook_orders
    ADD CONSTRAINT FK_EBOOK_ORDERS_ON_EBOOK FOREIGN KEY (ebook_id) REFERENCES ebooks (id);

ALTER TABLE ebook_orders
    ADD CONSTRAINT FK_EBOOK_ORDERS_ON_EBOOK_VERSION FOREIGN KEY (ebook_version_id) REFERENCES ebook_versions (id);

ALTER TABLE ebook_orders
    ADD CONSTRAINT FK_EBOOK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE ebook_versions
    ADD CONSTRAINT FK_EBOOK_VERSIONS_ON_EBOOK FOREIGN KEY (ebook_id) REFERENCES ebooks (id);

ALTER TABLE generated_plans
    ADD CONSTRAINT FK_GENERATED_PLANS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE generated_plans
    ADD CONSTRAINT FK_GENERATED_PLANS_ON_TRAVEL_PLAN FOREIGN KEY (travel_plan_id) REFERENCES travel_plans (id);

ALTER TABLE generated_plans
    ADD CONSTRAINT FK_GENERATED_PLANS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE travel_plan_questionnaires
    ADD CONSTRAINT FK_TRAVEL_PLAN_QUESTIONNAIRES_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE travel_plan_questionnaires
    ADD CONSTRAINT FK_TRAVEL_PLAN_QUESTIONNAIRES_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE travel_plan_questionnaires
    ADD CONSTRAINT FK_TRAVEL_PLAN_QUESTIONNAIRES_ON_TRAVEL_PLAN FOREIGN KEY (travel_plan_id) REFERENCES travel_plans (id);

ALTER TABLE travel_plan_questionnaires
    ADD CONSTRAINT FK_TRAVEL_PLAN_QUESTIONNAIRES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE organizations CASCADE;

DROP TABLE travel_requests CASCADE;