ALTER TABLE travel_requests
    DROP CONSTRAINT fkcs3gys6ke30muayb6wisrs5jo;

ALTER TABLE travel_requests
    DROP CONSTRAINT fkhi0yp6pmir6msshe80hkj3x4u;

CREATE TABLE contacts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    name         VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    subject      VARCHAR(255)                            NOT NULL,
    message      TEXT                                    NOT NULL,
    inquiry_type VARCHAR(255)                            NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    ip_address   VARCHAR(255),
    user_agent   VARCHAR(255),
    CONSTRAINT pk_contacts PRIMARY KEY (id)
);

CREATE TABLE credit_requests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    credits_requested INTEGER,
    reason            VARCHAR(255),
    status            VARCHAR(255),
    submitted_at      TIMESTAMP WITHOUT TIME ZONE,
    company_id        BIGINT,
    employee_id       BIGINT,
    CONSTRAINT pk_credit_requests PRIMARY KEY (id)
);

CREATE TABLE newsletter_subscribers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255)                            NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_newsletter_subscribers PRIMARY KEY (id)
);

ALTER TABLE newsletter_subscribers
    ADD CONSTRAINT uc_newsletter_subscribers_email UNIQUE (email);

ALTER TABLE credit_requests
    ADD CONSTRAINT FK_CREDIT_REQUESTS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE credit_requests
    ADD CONSTRAINT FK_CREDIT_REQUESTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

DROP TABLE organizations CASCADE;

DROP TABLE travel_requests CASCADE;